
spring:
  datasource:
    url: jdbc:postgresql://192.168.59.103:5432/postgres
    username: p2k12
    password: password
    driver-class-name: org.postgresql.Driver

management:
  context-path: /manage
